### ISSUE TITLE
Not recieving email for a token

### ISSUE THREAD

**Issue by absane** [cyllective/egress0r#3]
I submitted a request for a token to use this tool but I am not receiving the email after waiting 15 minutes. Is this an automated process that is broken or am I just impatient?

**Comment by cydave** [comment]
Sorry for my late reply, yes it appears our email server has some troubles. I will look into it.

**Edit:** Try again if you get the chance. Should you still have not received your token after around 15 minutes, you're free to PM me on twitter and I'll generate one for you for the time being.
